# Generated by Django 3.0.5 on 2020-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='userID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
